### PR TITLE
Initial Implementation of Trigger jobs based on data availability

### PR DESCRIPTION
**Pull request by tech3371**
# Change Summary
This PR setups a minimal processing pipeline infrastructure using lambda, and step function. This is a draft version. Post SIT-2, it will be evaluated again through SPIKE and implement based on SPIKE outcome.
## Overview
This processing pipeline uses lambda to make database query and perform processing work. 

There are two lambdas:
1. First one makes query to DynamoDB database and look for any data whose processing status is pending. And based on query result, it returns status code, 200 for success, 204 for empty result, and 404 for any other cases.
2. Second one takes in instrument name from lambda event dictionary. Based on value from input, it decom SWE packet if instrument name matches 'swe' and return status equal succeeded or else return status equal failed.

Then step function is used to orchastrate processing flow. This is what processing flow looks like on step function.
stepfunctions_graph (11)

## New Files
- step_function_stack.py
   - This file creates resources it needs to invoke in step function. Then it creates state machine defintion (AKA process flow) using step function task and choices combination.
- lambda_stack.py
    - This file creates lambda that uses image built from repo directory.
- sds_data_manager/lambda_images/*
    - This folder contains sub folders. Each sub folder contains Dockerfile and code for their respective lambda.

## Updated Files

- stack_builder.py
   - Added step function stack to the file.

## Testing
TODO: add tests

### CODE REVIEW

**Comment by tech3371** [comment]
pre-commit.ci autofix

**Review by GFMoraga — APPROVED** [review]
I am not an expert, but this looks simple enough as a baseline. Also, based on the info you mentioned yesterday.

**Review by maxinelasp — APPROVED** [review]

**Comment by tech3371** [comment]
pre-commit.ci autofix

**Review by sdhoyt — APPROVED** [review]

**Comment by tech3371** [comment]
pre-commit.ci autofix

**Comment by tech3371** [comment]
Thank you guys for bearing through this! I am going to merge this now.

**Pull request merged**
