### PR TITLE
MNT: Style updates

### PR DESCRIPTION
**Pull request by greglucas**
This adds pre-commit hooks for forcing a common style throughout the codebase.

I personally prefer this when working on larger projects to keep consistency, but definitely open to changing or removing some defaults/configurations if people aren't fans of this.

### CODE REVIEW

**Comment by tech3371** [comment]
> This adds pre-commit hooks for forcing a common style throughout the codebase.
> 
> I personally prefer this when working on larger projects to keep consistency, but definitely open to changing or removing some defaults/configurations if people aren't fans of this.

I like consistency in code. How are you checking if your code is in the format we want? I use VSCode. Will it check in VSCode and other like PyCharm?

**Comment by greglucas** [comment]
Yes, black is an auto-formatter available in vscode and pycharm. And ruff is just a faster version of many linting tools (pylint + flake8 + isort + others) which has a vscode extension.
https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff

This adds some tests to make sure we are all following the style before merging and tells you where the error is if something is wrong. (see the additional pre-commit.ci check above) if you want pre-commit.ci to fix your mistakes for you, you can comment `pre-commit.ci autofix` and the bot will make a commit for you too)

**Comment by tech3371** [comment]
> Yes, black is an auto-formatter available in vscode and pycharm. And ruff is just a faster version of many linting tools (pylint + flake8 + isort + others) which has a vscode extension. https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff
> 
> This adds some tests to make sure we are all following the style before merging and tells you where the error is if something is wrong. (see the additional pre-commit.ci check above) if you want pre-commit.ci to fix your mistakes for you, you can comment `pre-commit.ci autofix` and the bot will make a commit for you too)

Yeah. I have about "black". I used flake8 but recently changed to vscode version of PEP8. But I am looking forward to try this formatter.

**Review by tech3371 — APPROVED** [review]
It looks good to me!

**Review by sdhoyt — APPROVED** [review]

**Comment by greglucas** [comment]
Discussed on the call today, will hold off merging until the other 3 PRs are merged.

**Review by maxinelasp — APPROVED** [review]

**Pull request merged**
