### PR TITLE
SIT-2 Release [main]

### PR DESCRIPTION
**Pull request by bourque**
This PR marks the release of version `2.0.0`, which corresponds to the completion of SIT-2. This PR is being merged back into `main` per the nominal [git & GitHub workflow](https://imap-processing.readthedocs.io/en/latest/development/style-guide/git-and-github-workflow.html#git-and-github-workflow) and [release workflow](https://imap-processing.readthedocs.io/en/latest/development/release-workflow.html).

These are the release notes that will go into the GitHub release:

```
This release marks the successful completion of SIT-2. Further information about what was tested in SIT-2 can be found in this [galaxy page](https://lasp.colorado.edu/galaxy/display/IMAP/SDC-SIT-2) and the [SIT-2 GitHub Project Board](https://github.com/orgs/IMAP-Science-Operations-Center/projects/2/views/4)

## Features
* Ability to deploy and test software in the SDC Staging environment.
* Software can be successfully promoted from the SDC Staging Environment to the SDC Data Production Environment.
* Delivery of data files to the SPDF for routine archival purposes.
    * Backing up both OpenSearch and the data bucket to the backup account.
* Use of the API data interfaces by both SDC personnel as well as instrument teams. APIs:
    * The `/upload` endpoint for uploading new data to SDC
    * The `/download` endpoint for downloading data from SDC
    * The `/query` endpoint for querying information about data and data location.
* Demonstrate the SDC's ability to trigger jobs based on data availability and launch necessary processing containers.
    * Implementing a data watcher (Database) that keeps track of processing status.
    * Establishing a processing pipeline that initiates processing tasks.
```
    
    
I think all that needs to be 'reviewed' is to make sure this PR is merging in the appropriate changes into `main`, and not so much the contents.

### CODE REVIEW

**Comment by bourque** [comment]
@IMAP-Science-Operations-Center/imap-sdc This is a new branch/PR for the release that was branched off of commit 58f775555f0c9eb9700b87c92f8cc2b14bae2750, which reflects the end of SIT-2. Apologies for the duplication of review here!

**Comment by greglucas** [comment]
It looks like we pushed commits to main after SIT-1, but we never brought those back into dev.

https://github.com/IMAP-Science-Operations-Center/sds-data-manager/compare/dev...main

I think you'll need to manually resolve the conflict, ideally (?) with a new commit instead of changing a previous one so that we can keep all of the commit hashes around.

**Comment by bourque** [comment]
@greglucas So if I am understanding this correctly, we added the file `sds_in_a_box/sds_in_a_box_stack.py` to `main` about 6 months ago, but it does not currently exist in `dev`.

Do we want to keep `sds_in_a_box_stack.py` around or remove it? I don't have the historical context to know if this file is important/being used, or should be removed.

**Comment by greglucas** [comment]
Ahh, I see now! That is because we renamed and moved everything around. The important change is that we have the block public access code. Which it looks like is in our current repo: https://github.com/IMAP-Science-Operations-Center/sds-data-manager/blob/c02828252774cdb61a1721dd3874bbac7bc0c74e/sds_data_manager/stacks/sds_data_manager_stack.py#L78

So, yes, you can delete that file since it has been refactored.

**Comment by laspsandoval** [comment]
Really minor:

* Use of the API data interfaces by both SDC personnel as well as instrument teams. APIs:
    * The `/upoad` endpoint for uploading new data to SDC
    
Incorrect spelling: upload

**Review by laspsandoval — APPROVED** [review]

**Comment by bourque** [comment]
> Really minor:
> 
>     * Use of the API data interfaces by both SDC personnel as well as instrument teams. APIs:
>       
>       * The `/upoad` endpoint for uploading new data to SDC
> 
> 
> Incorrect spelling: upload

I'll make sure to fix this in the release notes!

**Pull request merged**
